Assignment from Dr. Paúl Pauca's CSC375: Deep Learning & Neural Network Class. All credit to him.

# Multi-class classification via unsupervised methods
In this project, we experiment with unsupervised machine learning methods for solving a multi-class classification problem. Unsupervised methods are computational methods that classify or cluster data by discovering hidden patterns or structure within the data itself, without the help of labeled training data. Unsupervised methods are widely used in data science applications in a variety of fields (medicine, finance, e-commerce, etc.) where labeled training data might be hard to obtain.

Here, we are going to apply a well-known unsupervised technique called hierarchical clustering and k-means clustering to the MNIST dataset multi-class classification problem. All the code and experimentation will be done in this Jupyter notebook.

# Multi-class classification: the MNIST dataset

The MNIST dataset consists of 70,000 gray-scale images (samples) of hand-written digits 0 through 9. The multi-class classification problem consists of classifying each sample accurately as belonging to one of ten classes. For the purpose of this assignment, we will only use the labels provided for each sample in the dataset for determining classification accuracy of our results.

# Part 1: Hierarchical Clustering

Hierarchical clustering is a well-known technique used heavily in data science applications. A cluster is a subset of the data which are deemed to be similar (in some sense). Clustering methods divide a dataset into clusters in such a way that the members of the same cluster are more similar to each other than to members of other clusters. Hierarchical clustering can be either top-down or bottom-up. The top-down (or divisive) approach starts with all the data in a single cluster and then successively divides clusters into smaller ones as it goes down the hierarchy. In contrast, the bottom-up (or agglomerative) approach starts with each sample in its own cluster and then pairs of clusters are merged as it goes up the hierarchy.



In [ ]:
#Import required libraries
import numpy as np
import pandas as pd

import scipy
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import cophenet
from scipy.spatial.distance import pdist

from pylab import rcParams
import seaborn as sb
import matplotlib.pyplot as plt

import sklearn
from sklearn.cluster import AgglomerativeClustering
import sklearn.metrics as sm
from sklearn.metrics import confusion_matrix

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
#Get required data
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

#Create a batch of training data of size 10,000
X_train = np.asarray(train_images.reshape(train_images.shape[0],-1))
X_batch= X_train[0:10000,:]

#Create a batch of the corresponding correct labels of size 10,000
y = train_labels
y_prec = train_labels[0:10000]

#Ensure this subset is a roughly accurate representation of the whole dataset
print(np.asarray(np.unique(y_prec, return_counts=True)))


11493376/11490434 [==============================] - 0s 0us/step
[[   0    1    2    3    4    5    6    7    8    9]
 [1001 1127  991 1032  980  863 1014 1070  944  978]]


In [ ]:
#mapCluster method to determine the correct cluster to compute accuracy

def mapCluster(y_clusters, y, numClusters):
  y_pred = np.zeros(y_clusters.shape).astype(np.int32)
  mapOfCluster = np.zeros(numClusters).astype(np.int32) * -1
  #Map clusters to digits in mapOfClusters by choosing the digit most often associated with each cluster
  for cluster in range(0, numClusters):
    #Count number of true labels for each member in this cluster
    count = np.bincount(y[y_clusters == cluster], minlength=10)
    #Map cluster to the true label of most cluster members
    #Pick the index of the first max valuein count if there are more than max values
    mapOfCluster[cluster] = np.argmax(count)

    # print(cluster, "map to", y_pred[cluster], ", counts: ", count)

  #Now use mapOfCluster to map each y_cluster to predicted class
  y_pred = mapOfCluster[y_clusters]
  #This is the loop version of the line above
  # for i in range(0, len(y_clusters)):
    #     y_pred[i] = mapOfCluster[y_clusters[i]]

  return y_pred

# Parameters Used

All combination of affinity and linkage will be tried to determine the best parameters. The available options are “euclidean”, “l1”, “l2”, “manhattan”, “cosine”, or “precomputed” for affinity and “ward”, “complete”, “average”, “single” for linkage. Note: Ward linkage can only be used in combination with euclidean affinity.

In [ ]:
#Try euclidean ward

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='euclidean', linkage='ward')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)


0.6958


array([[ 979,    1,    1,    6,    2,    0,    9,    0,    3,    0],
       [   0, 1088,   12,    5,    1,    0,    0,   19,    2,    0],
       [  13,    2,  885,    9,    2,    0,    1,   66,   13,    0],
       [   1,    0,    9,  961,    5,    0,    1,   32,   23,    0],
       [   0,    1,    2,    0,  470,    0,   16,  491,    0,    0],
       [   2,    0,    3,  277,    3,    0,    9,  323,  246,    0],
       [  10,    1,    1,   13,    2,    0,  978,    1,    8,    0],
       [   0,    3,    2,    7,   40,    0,    0, 1018,    0,    0],
       [   2,    4,    3,  279,   11,    0,    6,   60,  579,    0],
       [   1,    1,    2,   20,  395,    0,    2,  555,    2,    0]])

In [ ]:
#Try using Euclidean Ward with all data to see if results change

for i in range(6):
  #Create a batch of training data of size 10,000 from first 10,000
  X_train = np.asarray(train_images.reshape(train_images.shape[0],-1))
  X_batch= X_train[(i * 10000):((i*10000) +10000),:]

  #Create a batch of the corresponding correct labels of size 10,000
  y = train_labels
  y_prec = train_labels[(i * 10000):((i*10000) +10000)]

  # Compute hierarchical clustering
  numClusters = 10
  Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='euclidean', linkage='ward')
  Hclustering.fit(X_batch)

  # map the clusters to their digit of maximum frequency in the MNIST dataset
  clusters = Hclustering.labels_
  y_pred = mapCluster(clusters, y_prec, numClusters)
  print('Subset [', i*10000, ':', (i*10000+10000), ']: ', sm.accuracy_score(y_pred, y_prec))

Subset [ 0 : 10000 ]:  0.6958
Subset [ 10000 : 20000 ]:  0.6378
Subset [ 20000 : 30000 ]:  0.6378
Subset [ 30000 : 40000 ]:  0.6352
Subset [ 40000 : 50000 ]:  0.6388
Subset [ 50000 : 60000 ]:  0.6949


In [ ]:
#Try euclidean/L2 average

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='euclidean', linkage='average')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.2297


array([[ 960,   31,    0,    0,    0,    0,    9,    0,    0,    1],
       [   0, 1126,    0,    0,    0,    0,    0,    0,    1,    0],
       [   7,  978,    0,    0,    0,    0,    3,    0,    2,    1],
       [   6,  957,    0,   68,    0,    0,    0,    0,    0,    1],
       [   0,  959,    0,    0,    3,    0,   18,    0,    0,    0],
       [   4,  833,    0,   23,    0,    0,    2,    0,    1,    0],
       [   7,  877,    0,    5,    0,    0,  125,    0,    0,    0],
       [   0, 1068,    0,    0,    0,    0,    1,    0,    0,    1],
       [  14,  919,    0,    2,    0,    0,    0,    0,    9,    0],
       [   5,  958,    0,    1,    0,    0,    8,    0,    0,    6]])

In [ ]:
#Try euclidean/L2 complete

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='euclidean', linkage='complete')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.4109


array([[ 860,   36,    8,   37,   12,    0,   48,    0,    0,    0],
       [   0, 1117,    0,    1,    0,    0,    4,    0,    5,    0],
       [  21,   93,  546,  154,    6,    0,  115,    0,   56,    0],
       [  31,  234,   36,  586,    4,    0,  127,    0,   14,    0],
       [   0,  475,    8,    2,  491,    0,    3,    0,    1,    0],
       [  15,  493,    1,  237,    6,    0,  108,    0,    3,    0],
       [   8,  432,  178,   12,  156,    0,  228,    0,    0,    0],
       [   0,  824,    2,    8,  212,    0,    4,    0,   20,    0],
       [  10,  267,    3,  305,   22,    0,   56,    0,  281,    0],
       [   5,  664,    0,   17,  284,    0,    4,    0,    4,    0]])

In [ ]:
#Try euclidean/L2 single

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='euclidean', linkage='single')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.1136


array([[   0, 1001,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1127,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  991,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1030,    0,    2,    0,    0,    0,    0,    0,    0],
       [   0,  979,    0,    0,    1,    0,    0,    0,    0,    0],
       [   0,  862,    0,    0,    0,    1,    0,    0,    0,    0],
       [   0, 1014,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1070,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  941,    0,    0,    0,    0,    0,    0,    3,    0],
       [   0,  976,    0,    0,    0,    0,    0,    0,    0,    2]])

In [ ]:
#Try manhattan/L1 average

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='manhattan', linkage='average')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.2287


array([[ 963,   34,    0,    0,    0,    0,    4,    0,    0,    0],
       [   0, 1126,    0,    0,    0,    0,    0,    0,    1,    0],
       [   5,  978,    1,    0,    0,    0,    5,    0,    2,    0],
       [  10,  939,    0,   82,    0,    0,    1,    0,    0,    0],
       [   0,  976,    0,    0,    0,    0,    4,    0,    0,    0],
       [  30,  797,    0,   36,    0,    0,    0,    0,    0,    0],
       [  13,  897,    0,    0,    0,    0,  104,    0,    0,    0],
       [   0, 1070,    0,    0,    0,    0,    0,    0,    0,    0],
       [  17,  914,    1,    1,    0,    0,    1,    0,   10,    0],
       [   6,  969,    1,    1,    0,    0,    0,    0,    0,    1]])

In [ ]:
#Try manhattan/L1 complete

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='manhattan', linkage='complete')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.3649


array([[667,  41,   0, 274,   6,   0,  13,   0,   0,   0],
       [  3, 939, 181,   4,   0,   0,   0,   0,   0,   0],
       [111, 137, 613,  30,   3,   0,  97,   0,   0,   0],
       [  8, 445,  18, 556,   1,   0,   4,   0,   0,   0],
       [  0, 638,   7,   5, 328,   0,   2,   0,   0,   0],
       [ 25, 557,   1, 268,  11,   0,   1,   0,   0,   0],
       [  6, 119,   0, 278,  65,   0, 546,   0,   0,   0],
       [ 74, 897,   2,   3,  91,   0,   3,   0,   0,   0],
       [ 90, 582,   0, 251,  12,   0,   9,   0,   0,   0],
       [  3, 805,   0,  10, 158,   0,   2,   0,   0,   0]])

In [ ]:
#Try manhattan/L1 single

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='manhattan', linkage='single')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.1136


array([[   0, 1001,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1127,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  991,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1030,    0,    2,    0,    0,    0,    0,    0,    0],
       [   0,  980,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  862,    0,    0,    0,    1,    0,    0,    0,    0],
       [   0, 1014,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1070,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  939,    0,    0,    0,    0,    0,    0,    5,    0],
       [   0,  977,    0,    0,    0,    0,    0,    0,    0,    1]])

In [ ]:
#Try cosine average

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='cosine', linkage='average')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.2222


array([[   2,    1,    0,    0,    0,    0,    6,  992,    0,    0],
       [   0, 1108,    0,    0,    0,    0,    0,   19,    0,    0],
       [   0,   31,    9,    0,    0,    0,    2,  949,    0,    0],
       [   1,   11,    3,    1,    0,    0,    0, 1016,    0,    0],
       [   0,   20,    0,    0,   11,    0,    8,  941,    0,    0],
       [   0,  345,    0,    1,    0,    0,    1,  516,    0,    0],
       [   0,   12,    0,    0,    0,    0,   36,  966,    0,    0],
       [   0,   15,    0,    0,    0,    0,    0, 1055,    0,    0],
       [   0,   22,    0,    1,    0,    0,    0,  921,    0,    0],
       [   0,    6,    2,    0,    0,    0,    2,  968,    0,    0]])

In [ ]:
#Try cosine complete

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='cosine', linkage='complete')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.3853


array([[ 952,    1,    0,    0,    0,    0,   47,    1,    0,    0],
       [   0, 1115,    0,    0,    0,    0,    8,    4,    0,    0],
       [  59,  231,    0,    0,    0,    1,  684,   16,    0,    0],
       [ 169,  647,    0,    0,    0,    0,  183,   33,    0,    0],
       [  53,   27,    0,    0,    0,   39,  241,  620,    0,    0],
       [ 152,  478,    0,    0,    0,   96,   60,   77,    0,    0],
       [ 117,    9,    0,    0,    0,    1,  753,  134,    0,    0],
       [  48,   42,    0,    0,    0,    3,   40,  937,    0,    0],
       [ 124,  557,    0,    0,    0,   15,  130,  118,    0,    0],
       [  41,   59,    0,    0,    0,    0,  192,  686,    0,    0]])

In [ ]:
#Try cosine single

# Compute hierarchical clustering
numClusters = 10
Hclustering = AgglomerativeClustering(n_clusters=numClusters, affinity='cosine', linkage='single')
Hclustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = Hclustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.1136


array([[   0, 1001,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1127,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  990,    1,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1032,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  980,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,  859,    0,    0,    0,    4,    0,    0,    0,    0],
       [   0, 1013,    0,    0,    0,    0,    1,    0,    0,    0],
       [   0, 1069,    0,    0,    0,    0,    0,    1,    0,    0],
       [   0,  943,    0,    0,    0,    0,    0,    0,    1,    0],
       [   0,  977,    0,    0,    0,    0,    0,    0,    0,    1]])

## Part 2: Exploring K-means clustering

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import sklearn
from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import scale

import sklearn.metrics as sm
from sklearn import datasets
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.cluster import MeanShift

In [ ]:
#Get required data
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

#Create a batch of training data of size 10,000
X_train = np.asarray(train_images.reshape(train_images.shape[0],-1))
X_batch=X_train[0:10000,:]

#Create a batch of the corresponding correct labels of size 10,000
y = train_labels
y_prec = train_labels[0:10000]

In [ ]:
#mapCluster method given to us by Dr. Pauca

def mapCluster(y_clusters, y, numClusters):
  y_pred = np.zeros(y_clusters.shape).astype(np.int32)
  mapOfCluster = np.zeros(numClusters).astype(np.int32) * -1
  #Map clusters to digits in mapOfClusters by choosing the digit most often associated with each cluster
  for cluster in range(0, numClusters):
    #Count number of true labels for each member in this cluster
    count = np.bincount(y[y_clusters == cluster], minlength=10)
    #Map cluster to the true label of most cluster members
    #Pick the index of the first max valuein count if there are more than max values
    mapOfCluster[cluster] = np.argmax(count)

    # print(cluster, "map to", y_pred[cluster], ", counts: ", count)

  #Now use mapOfCluster to map each y_cluster to predicted class
  y_pred = mapOfCluster[y_clusters]
  #This is the loop version of the line above
  # for i in range(0, len(y_clusters)):
    #     y_pred[i] = mapOfCluster[y_clusters[i]]

  return y_pred

In [ ]:
#Try K-Means

#Create a batch of training data of size 10,000
X_train = np.asarray(train_images.reshape(train_images.shape[0],-1))
X_batch=X_train[0:10000,:]

# Compute hierarchical clustering
numClusters = 10
clustering = KMeans(n_clusters = numClusters, random_state= 1234)
clustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = clustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.5677


array([[ 787,    5,    8,   44,   18,    0,   40,    3,   96,    0],
       [   0, 1119,    2,    1,    1,    0,    0,    2,    2,    0],
       [   7,  181,  662,   61,   22,    0,   23,   11,   24,    0],
       [   6,  100,   30,  601,   11,    0,    9,   35,  240,    0],
       [   0,   67,    4,    0,  378,    0,   13,  517,    1,    0],
       [   9,  256,    2,  234,   28,    0,   22,   80,  232,    0],
       [  14,  121,    9,    5,   98,    0,  754,    0,   13,    0],
       [   1,   86,    4,    1,  105,    0,    0,  872,    1,    0],
       [   4,  118,    8,  209,   30,    0,   18,   53,  504,    0],
       [   5,   34,    0,   17,  239,    0,    3,  678,    2,    0]])

In [ ]:
#Try K-Means

# Compute hierarchical clustering
numClusters = 10
clustering = KMeans(n_clusters = numClusters, random_state= 5)
clustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = clustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.5675


array([[ 786,    5,    7,   47,   16,    0,   40,    3,   97,    0],
       [   0, 1119,    2,    1,    1,    0,    0,    2,    2,    0],
       [   7,  180,  664,   60,   22,    0,   23,   11,   24,    0],
       [   6,   99,   30,  597,   12,    0,    9,   34,  245,    0],
       [   0,   66,    4,    0,  377,    0,   14,  519,    0,    0],
       [   9,  255,    2,  233,   29,    0,   22,   81,  232,    0],
       [  14,  120,    9,    5,   96,    0,  757,    0,   13,    0],
       [   1,   87,    4,    1,  105,    0,    0,  871,    1,    0],
       [   4,  118,    8,  207,   31,    0,   18,   54,  504,    0],
       [   5,   34,    0,   17,  241,    0,    3,  676,    2,    0]])

In [ ]:
#Try K-Means with random-state = 5, max_iter = batch size

# Compute hierarchical clustering
numClusters = 10
clustering = KMeans(n_clusters = numClusters, random_state= 5, max_iter= 10000)
clustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = clustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.5675


array([[ 786,    5,    7,   47,   16,    0,   40,    3,   97,    0],
       [   0, 1119,    2,    1,    1,    0,    0,    2,    2,    0],
       [   7,  180,  664,   60,   22,    0,   23,   11,   24,    0],
       [   6,   99,   30,  597,   12,    0,    9,   34,  245,    0],
       [   0,   66,    4,    0,  377,    0,   14,  519,    0,    0],
       [   9,  255,    2,  233,   29,    0,   22,   81,  232,    0],
       [  14,  120,    9,    5,   96,    0,  757,    0,   13,    0],
       [   1,   87,    4,    1,  105,    0,    0,  871,    1,    0],
       [   4,  118,    8,  207,   31,    0,   18,   54,  504,    0],
       [   5,   34,    0,   17,  241,    0,    3,  676,    2,    0]])

In [ ]:
#Try K-Means with random-state = 5, max_iter = batch size

# Compute hierarchical clustering
numClusters = 10
clustering = KMeans(n_clusters = numClusters, random_state= 5, algorithm="full")
clustering.fit(X_batch)

# map the clusters to their digit of maximum frequency in the MNIST dataset
clusters = clustering.labels_
y_pred = mapCluster(clusters, y_prec, numClusters)
print(sm.accuracy_score(y_pred, y_prec))
confusion_matrix(y_prec, y_pred)

0.5675


array([[ 786,    5,    7,   47,   16,    0,   40,    3,   97,    0],
       [   0, 1119,    2,    1,    1,    0,    0,    2,    2,    0],
       [   7,  180,  664,   60,   22,    0,   23,   11,   24,    0],
       [   6,   99,   30,  597,   12,    0,    9,   34,  245,    0],
       [   0,   66,    4,    0,  377,    0,   14,  519,    0,    0],
       [   9,  255,    2,  233,   29,    0,   22,   81,  232,    0],
       [  14,  120,    9,    5,   96,    0,  757,    0,   13,    0],
       [   1,   87,    4,    1,  105,    0,    0,  871,    1,    0],
       [   4,  118,    8,  207,   31,    0,   18,   54,  504,    0],
       [   5,   34,    0,   17,  241,    0,    3,  676,    2,    0]])